# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c421a0b8cc50e45d380fe15ff068be7a8d147fd46d80dce729bc14bdfcb5e3d35e962494a5f7a7be81e50eb48059114c112484edea553924df4ce0cfc67d5e

test:
  secret_key_base: b7f8eeaa73981cd1a218bba382b1e4e7a92bf450b60093e6cd935f189106c95fae475156f1c53e1533203a282d5dca9208bf7b81b47491bd0eac6bfd57ae070e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
